<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="InterfazRepo\" />
    <Folder Include="ServiciosRepo\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
